export  const GET_COMMENTS_REQUEST = 'COMMENTS:GET_COMMENTS_REQUEST';
export  const GET_COMMENTS_SUCCESS = 'COMMENTS:GET_COMMENTS_SUCCESS';
export  const GET_COMMENTS_FAILURE = 'COMMENTS:GET_COMMENTS_FAILURE';
export  const GET_COMMENTS_LOADING = 'COMMENTS:GET_COMMENTS_LOADING';

export const REGISTER_LOADING ='REGISTER_LOADING';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAILURE ='REGISTER_FAILURE';

export const LOGIN_LOADING ='LOGIN_LOADING';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';

export const LOGOUT_LOADING ='LOGOUT_LOADING';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const LOGOUT_FAILURE ='LOGOUT_FAILURE';

export const FIREBASE_MESSAGE_ADD_LOADING ='FIREBASE_MESSAGE_ADD_LOADING';
export const FIREBASE_MESSAGE_ADD_SUCCESS ='FIREBASE_MESSAGE_ADD_SUCCESS';
export const FIREBASE_MESSAGE_ADD_FAILURE ='FIREBASE_MESSAGE_ADD_FAILURE';

export const GET_FIREBASE_MESSAGES_LOADING ='GET_FIREBASE_MESSAGES_LOADING';
export const GET_FIREBASE_MESSAGES_SUCCESS ='GET_FIREBASE_MESSAGES_SUCCESS';
export const GET_FIREBASE_MESSAGES_FAILURE ='GET_FIREBASE_MESSAGES_FAILURE';